// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEqJBTYNF2CpgXIJdqyJKfdYWKn7AYUEU',
    appId: '1:882774404966:web:7ce23b648e7e88053ea2a7',
    messagingSenderId: '882774404966',
    projectId: 'flutter-firebase-ce6b1',
    authDomain: 'flutter-firebase-ce6b1.firebaseapp.com',
    storageBucket: 'flutter-firebase-ce6b1.firebasestorage.app',
    measurementId: 'G-8DRDCT58F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCTNyzGCDY_GeKHcE-5DuPK9WbnDa7Zkg',
    appId: '1:882774404966:android:9f2e6fbdb67986663ea2a7',
    messagingSenderId: '882774404966',
    projectId: 'flutter-firebase-ce6b1',
    storageBucket: 'flutter-firebase-ce6b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHRqLVqJrXjklGHofXYxmloNNVDw_4r6M',
    appId: '1:882774404966:ios:7396bf26f61ee6363ea2a7',
    messagingSenderId: '882774404966',
    projectId: 'flutter-firebase-ce6b1',
    storageBucket: 'flutter-firebase-ce6b1.firebasestorage.app',
    iosBundleId: 'com.example.onlineDatabaseFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHRqLVqJrXjklGHofXYxmloNNVDw_4r6M',
    appId: '1:882774404966:ios:7396bf26f61ee6363ea2a7',
    messagingSenderId: '882774404966',
    projectId: 'flutter-firebase-ce6b1',
    storageBucket: 'flutter-firebase-ce6b1.firebasestorage.app',
    iosBundleId: 'com.example.onlineDatabaseFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEqJBTYNF2CpgXIJdqyJKfdYWKn7AYUEU',
    appId: '1:882774404966:web:d815dbc317893a1d3ea2a7',
    messagingSenderId: '882774404966',
    projectId: 'flutter-firebase-ce6b1',
    authDomain: 'flutter-firebase-ce6b1.firebaseapp.com',
    storageBucket: 'flutter-firebase-ce6b1.firebasestorage.app',
    measurementId: 'G-7D9NKR7EWR',
  );
}
